# Generated by Django 2.2.1 on 2021-02-09 16:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distancelearning', '0002_shedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feldhers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Список Лечебного дела',
                'verbose_name_plural': 'Список Лечебного дела',
            },
        ),
    ]
