# Generated by Django 2.2.1 on 2021-02-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distancelearning', '0005_predmets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmets',
            name='group',
            field=models.CharField(max_length=200, verbose_name='Название группы'),
        ),
    ]
