# Generated by Django 2.2.1 on 2021-02-03 10:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.CharField(max_length=200, verbose_name='Эл. почта')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Заявку на дополнительное образование',
                'verbose_name_plural': 'Заявка на дополнительное образование',
            },
        ),
    ]
