# Generated by Django 2.2.1 on 2021-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_callbackeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackeducation',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл'),
        ),
    ]
