# Generated by Django 2.2.1 on 2021-02-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210213_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Новости', 'Новости'), ('Объявление', 'Объявление')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
