# Generated by Django 2.2.1 on 2021-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Новости', 'Новости'), ('Объявление', 'Объявление')], max_length=10, verbose_name='Статус'),
        ),
    ]
