# Generated by Django 2.2.1 on 2021-03-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210304_1945'),
        ('home', '0005_auto_20210303_1556'),
    ]

    operations = [
    ]
