# Generated by Django 2.2.1 on 2021-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20210306_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=250, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
