# Generated by Django 2.2.1 on 2021-03-04 14:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вкладки')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок подвкладки')),
                ('title_article', models.CharField(max_length=250, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(max_length=250, verbose_name='Слаг')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('name_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.Tabs')),
            ],
        ),
    ]
