# Generated by Django 2.2.1 on 2021-03-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_tabs_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabs',
            old_name='slug',
            new_name='sections',
        ),
    ]
