# Generated by Django 2.2.1 on 2021-03-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0003_auto_20210305_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='my_field',
            field=models.BooleanField(default=False, verbose_name='Добавить форму обратной связи(по умолчанию False)'),
        ),
    ]
