# Generated by Django 2.2.1 on 2021-03-07 10:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0004_section_my_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема обращения')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.CharField(max_length=200, verbose_name='Эл. почта')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Файл')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
        ),
    ]
