# Generated by Django 2.2.1 on 2021-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_groups_predmets'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmets',
            name='slug',
            field=models.SlugField(default='', max_length=250, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
