# Generated by Django 2.2.1 on 2021-03-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0007_predmets_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmets',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг'),
        ),
    ]
