# Generated by Django 2.2.1 on 2021-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0009_auto_20210308_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='sections',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='Слаг'),
        ),
    ]
