# Generated by Django 2.2.1 on 2021-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0010_auto_20210313_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='Слаг'),
        ),
    ]
