# Generated by Django 2.2.1 on 2021-03-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_auto_20210313_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmets',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращение'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Подвкладку', 'verbose_name_plural': 'Подвкладка'},
        ),
        migrations.AlterModelOptions(
            name='tabs',
            options={'verbose_name': 'Вкладку', 'verbose_name_plural': 'Вкладка'},
        ),
        migrations.AlterField(
            model_name='section',
            name='title_article',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Predmets',
        ),
    ]
