# Generated by Django 2.2.1 on 2021-01-31 06:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_hotline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controls_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Контакты контролирующих организаций',
                'verbose_name_plural': 'Контакты контролирующих организаций',
            },
        ),
        migrations.AlterModelOptions(
            name='hotline',
            options={'verbose_name': 'Горячую линию', 'verbose_name_plural': 'Горячая линия'},
        ),
    ]
