# Generated by Django 2.2.1 on 2021-02-01 09:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Преподавателям/Справочная информация',
                'verbose_name_plural': 'Преподавателям/Справочная информация',
            },
        ),
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Контакты/Обратную связь(текст)', 'verbose_name_plural': 'Контакты/Обратная связь(текст)'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты/Контакты', 'verbose_name_plural': 'Контакты/Контакты'},
        ),
        migrations.AlterModelOptions(
            name='controls',
            options={'verbose_name': 'Контакты/Контакты контролирующих организаций', 'verbose_name_plural': 'Контакты/Контакты контролирующих организаций'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Контакты/Обратную связь(обращения)', 'verbose_name_plural': 'Контакты/Обратная связь(обращения)'},
        ),
        migrations.AlterModelOptions(
            name='hotline',
            options={'verbose_name': 'Контакты/Горячую линию', 'verbose_name_plural': 'Контакты/Горячая линия'},
        ),
    ]
