# Generated by Django 2.2.1 on 2021-02-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210201_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Преподавателям/Семинары', 'verbose_name_plural': 'Преподавателям/Семинары'},
        ),
    ]
