# Generated by Django 2.2.1 on 2021-02-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210201_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Обратную связь(текст)', 'verbose_name_plural': 'Обратная связь(текст)'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='controls',
            options={'verbose_name': 'Контакты контролирующих организаций', 'verbose_name_plural': 'Контакты контролирующих организаций'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Обратную связь(обращения)', 'verbose_name_plural': 'Обратная связь(обращения)'},
        ),
        migrations.AlterModelOptions(
            name='hotline',
            options={'verbose_name': 'Горячую линию', 'verbose_name_plural': 'Горячая линия'},
        ),
    ]
