# Generated by Django 2.2.1 on 2021-02-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студентам', 'verbose_name_plural': 'Студентам'},
        ),
    ]
