# Generated by Django 2.2.1 on 2021-02-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210206_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Вкладка - Студентам', 'verbose_name_plural': 'Вкладка - Студентам'},
        ),
    ]
