# Generated by Django 2.2.1 on 2021-02-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210211_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студентам', 'verbose_name_plural': 'Студентам'},
        ),
    ]
